/* Generated by tools/make_assets.py. */
#ifndef ASSETS_H
#define ASSETS_H
#define BG_TILE_HALFWORDS 14720
#define PANEL_TILE 417
#define PLAYER_TILE_HALFWORDS 2048
extern const unsigned short bg_palette[256];
extern const unsigned short bg_tiles[14720];
extern const unsigned short ground_map[4096];
extern const unsigned short foreground_map[4096];
extern const unsigned char collision_map[4096];
extern const unsigned short interior_ground_map[4096];
extern const unsigned short interior_foreground_map[4096];
extern const unsigned char interior_collision_map[4096];
extern const unsigned short font_tiles[64];
extern const unsigned short player_palette[16];
extern const unsigned short player_tiles[2048];
#endif
