#!/usr/bin/env python3
"""Convert the glass-building gym into GBA mode-4 art and collision."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
W, H = 240, 160
source = Image.open(ROOT / "art/recCenterInterior.jpg").convert("RGB")
room = source.resize((W, H), Image.Resampling.LANCZOS)

q = room.quantize(colors=252, method=Image.Quantize.MEDIANCUT,
                  dither=Image.Dither.NONE)
base_pal = q.getpalette()[:756]
base_pal += [0] * (756 - len(base_pal))
pal = base_pal + [24, 63, 57, 247, 236, 203,
                  87, 144, 122, 255, 255, 255]
q.putpalette(pal)
q.save(ROOT / "art/glass-gym-interior.png")
(ROOT / "source/gym_pixels.bin").write_bytes(q.tobytes())

# White is solid. The room floor is open and the bottom-center exit is passable.
mask = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(mask)
d.rectangle((4, 34, 233, 155), fill=0)
d.rectangle((104, 137, 142, 159), fill=0)
for rect in [
    (17, 58, 73, 123),    # weight bench on left
    (99, 52, 128, 105),   # treadmill in center
    (181, 53, 226, 115),  # exercise frame on right
]:
    d.rectangle(rect, fill=255)

small = mask.resize((W // 4, H // 4), Image.Resampling.NEAREST)
bits = bytearray((W // 4 * (H // 4) + 7) // 8)
for i, value in enumerate(small.tobytes()):
    if value:
        bits[i // 8] |= 1 << (i % 8)
(ROOT / "source/gym_collision.bin").write_bytes(bits)
mask.save(ROOT / "art/glass-gym-collision.png")

palette = [(pal[i] >> 3) | ((pal[i + 1] >> 3) << 5) |
           ((pal[i + 2] >> 3) << 10) for i in range(0, 768, 3)]
(ROOT / "source/gym_palette.h").write_text(
    "/* Generated by tools/make_gym.py. */\n"
    f"#define GYM_W {W}\n#define GYM_H {H}\n"
    "static const unsigned short gym_palette[256]={" +
    ",".join(map(str, palette)) + "};\n")
print("Built glass-building gym: 240x160 with authored collision.")
