#!/usr/bin/env python3
"""Convert the red-roof house room into GBA mode-4 art and collision."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
W, H = 240, 160
source = Image.open(ROOT / "art/red-house-interior-source.png").convert("RGB")
room = source.resize((W, H), Image.Resampling.LANCZOS)

# Reserve the final four indices for the existing pause-menu UI.
q = room.quantize(colors=252, method=Image.Quantize.MEDIANCUT,
                  dither=Image.Dither.NONE)
base_pal = q.getpalette()[:756]
base_pal += [0] * (756 - len(base_pal))
pal = base_pal + [24, 63, 57, 247, 236, 203,
                  87, 144, 122, 255, 255, 255]
q.putpalette(pal)
q.save(ROOT / "art/red-house-interior.png")
(ROOT / "source/interior_pixels.bin").write_bytes(q.tobytes())

# White is solid. The central floor and bottom doorway are walkable.
mask = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(mask)
d.rectangle((11, 47, 228, 143), fill=0)
d.rectangle((106, 137, 134, 159), fill=0)

# Furniture footprints. The rug remains walkable.
for rect in [
    (17, 27, 55, 55),     # bookcase
    (18, 57, 55, 116),    # bed
    (204, 20, 228, 54),   # plant
    (170, 64, 224, 96),   # writing table
    (187, 94, 211, 113),  # chair
]:
    d.rectangle(rect, fill=255)

small = mask.resize((W // 4, H // 4), Image.Resampling.NEAREST)
bits = bytearray((W // 4 * (H // 4) + 7) // 8)
for i, value in enumerate(small.tobytes()):
    if value:
        bits[i // 8] |= 1 << (i % 8)
(ROOT / "source/interior_collision.bin").write_bytes(bits)
mask.save(ROOT / "art/red-house-interior-collision.png")

palette = [(pal[i] >> 3) | ((pal[i + 1] >> 3) << 5) |
           ((pal[i + 2] >> 3) << 10) for i in range(0, 768, 3)]
(ROOT / "source/interior_palette.h").write_text(
    "/* Generated by tools/make_interior.py. */\n"
    f"#define INTERIOR_W {W}\n#define INTERIOR_H {H}\n"
    "static const unsigned short interior_palette[256]={" +
    ",".join(map(str, palette)) + "};\n")
print("Built red-roof house interior: 240x160 with authored collision.")
