#!/usr/bin/env python3
"""Build the animated Pittsburgh driving intro for GBA mode 4."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
TITLE_W, TITLE_H = 320, 160
CAR_W, CAR_H, CAR_FRAMES = 96, 42, 4

# Make an extra-wide panorama so the skyline can scroll behind the car.
bg = Image.open(ROOT / "art/steelhacks-pittsburgh.png").convert("RGB")
crop_h = int(bg.width / 2)
top = max(0, (bg.height - crop_h) // 2)
bg = bg.crop((0, top, bg.width, top + crop_h))
bg = bg.resize((TITLE_W, TITLE_H), Image.Resampling.LANCZOS)

# Prepare a small, crisp side-view car. The tyre silhouettes stay fixed between
# frames; only a tiny hub marker moves. Rotating the whole low-resolution wheel
# made its outside edge wobble and change shape.
source = Image.open(ROOT / "art/driving-car-source.png").convert("RGBA")
# Ignore faint stray alpha outside the generated sprite when finding its crop.
alpha_bounds = source.getchannel("A").point(lambda a: 255 if a >= 32 else 0)
source = source.crop(alpha_bounds.getbbox())
# Work at half resolution, then enlarge with nearest-neighbour pixels. Sampling
# with NEAREST is intentional: no blended edge pixels may enter the GBA sprite.
car = source.resize((CAR_W // 2, CAR_H // 2), Image.Resampling.NEAREST)

# Collapse the source to a tiny fixed palette before enlargement. This removes
# gradients and makes every body panel, window and outline read as hard pixel
# art against the more detailed skyline.
flat_palette = [
    (18, 20, 24),    # outline / tyres
    (255, 91, 0),    # body orange
    (153, 49, 43),   # tail light
    (111, 216, 218), # glass
    (73, 80, 88),    # dark metal
    (207, 210, 212), # wheel hubs
    (255, 221, 25),  # headlight
]
pixels = car.load()
for y in range(car.height):
    for x in range(car.width):
        r, g, b, a = pixels[x, y]
        if a < 128:
            pixels[x, y] = (0, 0, 0, 0)
            continue
        color = min(flat_palette,
                    key=lambda p: (r-p[0])**2 + (g-p[1])**2 + (b-p[2])**2)
        pixels[x, y] = (*color, 255)
car = car.resize((CAR_W, CAR_H), Image.Resampling.NEAREST)
wheel_centres = ((23, 34), (69, 34))
frames = []
hub_markers = ((0, -3), (3, 0), (0, 3), (-3, 0))
for marker_x, marker_y in hub_markers:
    frame = car.copy()
    draw = ImageDraw.Draw(frame)
    for cx, cy in wheel_centres:
        draw.ellipse((cx-4, cy-4, cx+4, cy+4), fill=(207, 210, 212, 255))
        draw.rectangle((cx-1, cy-1, cx+1, cy+1), fill=(73, 80, 88, 255))
        mx, my = cx + marker_x, cy + marker_y
        draw.rectangle((mx-1, my-1, mx, my), fill=(73, 80, 88, 255))
    frames.append(frame)

# Create one shared 252-colour palette for both the panorama and every frame.
swatches = Image.new("RGB", (TITLE_W, TITLE_H + CAR_H), (0, 0, 0))
swatches.paste(bg, (0, 0))
for i, frame in enumerate(frames):
    rgb = Image.new("RGB", frame.size, (8, 8, 20))
    rgb.paste(frame.convert("RGB"), mask=frame.getchannel("A"))
    swatches.paste(rgb, (i * CAR_W, TITLE_H))
palette_seed = swatches.quantize(colors=252, method=Image.Quantize.MEDIANCUT,
                                 dither=Image.Dither.NONE)
palette = palette_seed.getpalette()[:252*3]
palette += [20, 23, 35, 255, 255, 255, 255, 204, 71, 0, 0, 0]

palette_image = Image.new("P", (1, 1))
# Keep indices 252-255 unavailable to art. They belong to the UI and alpha.
palette_image.putpalette(palette[:252*3] + palette[:3] * 4)

def indexed(rgb):
    out = rgb.quantize(palette=palette_image, dither=Image.Dither.NONE)
    data = bytearray(out.tobytes())
    for i, value in enumerate(data):
        if value >= 252:
            data[i] = 0
    out.frombytes(bytes(data))
    out.putpalette(palette)
    return out

bg_indexed = indexed(bg)
bg_indexed.save(ROOT / "art/pittsburgh-drive.png")
(ROOT / "source/title_pixels.bin").write_bytes(bg_indexed.tobytes())

car_bytes = bytearray()
sheet = Image.new("RGBA", (CAR_W * CAR_FRAMES, CAR_H), (0, 0, 0, 0))
for i, frame in enumerate(frames):
    quant = indexed(frame.convert("RGB"))
    data = bytearray(quant.tobytes())
    alpha = frame.getchannel("A").tobytes()
    for p, a in enumerate(alpha):
        if a < 96:
            data[p] = 255
    car_bytes.extend(data)
    sheet.paste(frame, (i * CAR_W, 0), frame)
sheet.save(ROOT / "art/driving-car.png")
(ROOT / "source/car_frames.bin").write_bytes(car_bytes)

values = [(palette[i] >> 3) | ((palette[i+1] >> 3) << 5) |
          ((palette[i+2] >> 3) << 10) for i in range(0, 768, 3)]
(ROOT / "source/title_palette.h").write_text(
    "/* Generated by tools/make_title.py. */\n"
    f"#define TITLE_W {TITLE_W}\n#define TITLE_H {TITLE_H}\n"
    f"#define CAR_W {CAR_W}\n#define CAR_H {CAR_H}\n"
    f"#define CAR_FRAMES {CAR_FRAMES}\n"
    "static const unsigned short title_palette[256]={" +
    ",".join(map(str, values)) + "};\n")
print(f"Animated title: {TITLE_W}x{TITLE_H} panorama, "
      f"{CAR_FRAMES} car frames at {CAR_W}x{CAR_H}.")
