#!/usr/bin/env python3
"""Convert the supplied mountain-and-city map into GBA mode-4 data."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
W, H = 1208, 648
source = Image.open(ROOT / "art/map-polished.png").convert("RGB")
image = source.resize((W, H), Image.Resampling.NEAREST)

# Reserve the final four palette entries for the game UI.
q = image.quantize(colors=252, method=Image.Quantize.MEDIANCUT,
                   dither=Image.Dither.NONE)
base_pal = q.getpalette()[:756]
base_pal += [0] * (756 - len(base_pal))
pal = base_pal + [24, 63, 57, 247, 236, 203,
                  87, 144, 122, 255, 255, 255]
q.putpalette(pal)
q.save(ROOT / "art/city-map.png")
(ROOT / "source/city_pixels.bin").write_bytes(q.tobytes())

mask = Image.new("L", (W, H), 0)
d = ImageDraw.Draw(mask)
def box(rect, fill=255): d.rectangle(rect, fill=fill)
def poly(points, fill=255): d.polygon(points, fill=fill)

# Outer edge keeps the camera world bounded cleanly.
box((0, 0, W-1, 5)); box((0, H-6, W-1, H-1))
box((0, 0, 5, H-1)); box((W-6, 0, W-1, H-1))

# Mountain walls and raised western plateau. Stair and path gaps remain open.
box((6, 6, 500, 61))
poly([(6,55),(61,55),(61,285),(53,285),(53,310),(6,310)])
# The approved map joins these cliffs into one continuous impassable wall.
box((442,58,486,327))
box((6,302,254,327)); box((290,302,443,327))

# Houses and civic buildings on the western side.
for rect in [
    (80,64,141,130),(274,65,334,130),(340,64,424,130),
    (143,191,211,258),(322,193,379,259),
]: box(rect)

# Decorative fences, benches, signs and dense landscaping.
for rect in [
    (137,108,255,127),(61,290,137,307),(315,289,408,307),
    (421,245,433,289),(92,393,207,417),(315,392,455,416),
    (91,603,451,625),(229,493,250,516),
]: box(rect)

# Dense forest masses. Individual trees outside these masses are also solid.
poly([(487,6),(674,6),(674,95),(650,95),(650,113),(604,113),
      (604,129),(565,129),(565,151),(522,151),(522,196),(481,196)])
poly([(460,195),(589,195),(589,219),(614,219),(614,270),(588,270),
      (588,301),(548,301),(548,326),(458,326)])
poly([(6,327),(217,327),(217,355),(167,355),(167,380),(89,380),
      (89,579),(78,579),(78,640),(6,640)])
poly([(386,328),(635,328),(635,456),(456,456),(456,418),(386,418)])
poly([(458,516),(704,516),(704,640),(458,640)])

# Standalone large trees and bushes that should not be walked through.
for rect in [
    (126,42,174,98),(252,82,278,119),(270,154,302,207),
    (343,337,383,391),(398,342,432,389),(399,387,430,435),
    (540,233,589,285),(632,239,673,309),(644,325,681,423),
    (593,321,635,381),(472,506,526,577),(528,509,582,589),
    (582,516,630,600),(628,541,684,631),
]: box(rect)

# River and ponds. The stone bridge across the river is cut back to walkable.
poly([(655,6),(695,6),(695,86),(681,86),(681,113),(651,113),
      (651,133),(620,133),(620,303),(606,303),(606,329),(481,329),
      (481,303),(589,303),(589,121),(623,121),(623,96),(651,96)])
box((574,148,706,169), 0)
# The curved stone plaza enters from the west before crossing the lower bridge.
# Keep the whole visible paving open so the player can walk east from the exact
# spot shown in the collision report, not only after already reaching the span.
box((487,184,632,235), 0)
poly([(151,477),(224,472),(252,493),(252,548),(235,556),(178,556),
      (151,537)])
poly([(6,579),(78,579),(78,640),(101,640),(101,647),(6,647)])

# City buildings, kept separate so streets and sidewalks remain navigable.
BUILDINGS = [
    (727,49,810,159),(829,52,916,161),(924,52,987,161),
    (1000,51,1082,160),(1092,51,1177,161),
    (728,176,799,313),(832,181,925,314),(928,181,985,314),
    (986,231,1012,312),(1011,181,1083,314),(1097,181,1175,314),
    (835,329,926,485),(950,334,1012,484),(1011,328,1084,484),
    (1097,311,1177,598),(731,505,803,597),(834,505,930,598),
    (951,499,1073,598)
]
for rect in BUILDINGS: box(rect)

# Small city furniture and hedges.
for rect in [(707,286,731,311),(712,350,758,374),(790,493,810,521),
             (1060,135,1075,159),(790,120,810,150)]: box(rect)

# Four-pixel collision cells, matching the runtime lookup.
small = mask.resize((W//4, H//4), Image.Resampling.NEAREST)
bits = bytearray((W//4 * (H//4) + 7)//8)
for i, value in enumerate(small.tobytes()):
    if value:
        bits[i//8] |= 1 << (i % 8)
(ROOT / "source/city_collision.bin").write_bytes(bits)
mask.save(ROOT / "art/city-collision.png")

palette = [(pal[i] >> 3) | ((pal[i+1] >> 3) << 5) |
           ((pal[i+2] >> 3) << 10) for i in range(0, 768, 3)]
(ROOT / "source/city_palette.h").write_text(
    "/* Generated by tools/make_city.py. */\n"
    f"#define CITY_W {W}\n#define CITY_H {H}\n"
    "static const unsigned short city_palette[256]={" +
    ",".join(map(str, palette)) + "};\n")
print(f"Converted new map: {W}x{H}, 252 colors, authored collision.")
